config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
     registrations: 'users/registrations'
   }


   as :user do
     get 'sign-up', to: 'devise/registrations#new', as: :sign_up
     get 'sign-in', to: 'devise/sessions#new', as: :sign_in
     delete 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
     get 'profile', to: 'devise/registrations#edit', as: :profile
   end

  resources :episodes
  get '/seasons', to: 'episodes#seasons', as: :seasons
  get '/season/:number', to: 'episodes#season', as: :season
  get '/last-episode', to: 'episodes#last', as: :last_episode
  get '/search', to: 'episodes#search', as: :search
  get '/ebbasons', to: 'episode#ebbasons', as: :ebbasons
  root to: 'episodes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
# == Schema Information
#
# Table name: episodes
#
#  id         :integer          not null, primary key
#  season     :integer
#  number     :integer
#  name       :string
#  duration   :integer
#  synopsis   :text
#  image      :string
#  link       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Episode < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  def index
    @episodes = Episode.all
  end

  def show
  end

  def new
    @episode = Episode.new
  end

  def edit
  end

  def create
    @episode = Episode.new(episode_params)

    if @episode.save
      redirect_to @episode, notice: 'Episode was successfully created.'
    else
      render :new
    end
  end

  def update
    if @episode.update(episode_params)
      redirect_to @episode, notice: 'Episode was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @episode.destroy
    redirect_to episodes_url, notice: 'Episode was successfully destroyed.'
  end

  def season
    @number = params[:number]
    @episodes = Episode.where(season: @number)
  end

  def seasons
    @seasons = Episode.distinct.pluck(:season).sort
  end

  def last
    @episode = Episode.last
  end

  def search
    @query = params[:query]
    @episodes = Episode.where("name like ?", "%"+@query+"%")
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def episode_params
      params.require(:episode).permit(:season, :number, :name, :duration, :synopsis, :image, :link)
    end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update, :new]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # PUT /resource/:user_id/admin
  def admin
    @user = User.find(params[:user_id])
    if @user.update(admin: true)
      redirect_to root_path, notice: "Admin priviledges granted"
    else
      redirect_to root_path, notice: "User could not be made admin"
    end
  end

  # PUT /resource/:user_id/unadmin
  def unadmin
    @user = User.find(params[:user_id])
    if @user.update(admin: false)
      redirect_to root_path, notice: "Admin priviledges removed"
    else
      redirect_to root_path, notice: "User could not be made not admin"
    end
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :description, :image, :sex, :dob, :nationality, :address, :telephone])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
  def number_episodes(season)
    Episode.where(season:season).count
  end
end

app/views/episodes/_episode.html.haml
.row.bottom-bar-container
  .col-md-8.offset-md-2
    - @episodes.each do |episode|
      .card
        .card-body
          .row
            .col-3
              =image_tag episode.image, class: "img-fluid"
            .col-5
              %h4.text-center
                = episode.name
              %p.small.text-center
                = "Season #{episode.season}, Episode #{episode.number}"
                = link_to "Read More...", episode, class:"text-center"
                = link_to "Edit", edit_episode_path(episode), class:"text-center"
            .col-3
              .text-right
                = link_to "Watch", episode.link, class: "btn btn-primary"

app/views/episodes/_episode_details.html.haml
.row
  -e=@episode
  .col-md-5.offset-md-1.col-12
    =image_tag e.image, class: "img-fluid"
  .col-md-5
    %h3.text-center
      = e.name
    %p.small.text-center
      = "Season #{e.season}, Episode #{e.number}"
    .text-center
      = link_to "Watch episode", e.link, class: "btn btn-primary"
    .card
      .card-body
        %b Duracion:
        = "#{e.duration} min"
        %br
        = "Synopsis #{e.synopsis}"

app/views/episodes/_form.html.haml
= form_for @episode do |f|

  .bg-danger.pl-4.pr-4
    .form-group.pt-4
      - f.label :name
      = f.text_field :name, :placeholder => "Name", class: "form-control"
    .row
      .col-6.col-sm-6
        .form-group
          - f.label :season
          = f.number_field :season, :placeholder => "Season", class: "form-control"
      .col-6.col-sm-6
        .form-group
          - f.label :number
          = f.number_field :number, :placeholder => "Number", class: "form-control"
    .form-group
      - f.label :duration
      = f.number_field :duration,  :placeholder => "Duration (min)", class: "form-control"
    .form-group
      - f.label :synopsis
      = f.text_area :synopsis, :rows => "6",  :placeholder => "Synopsis", class: "form-control"
    .form-group
      - f.label :image
      = f.text_field :image,  :placeholder => "Image", class: "form-control"
    .form-group
      - f.label :link
      = f.text_field :link, :placeholder => "Link", class: "form-control"
    .text-center.pb-4
      = f.submit "Save", class: "btn btn-light"

app/views/episodes/edit.html.haml
.row
  .col-md-6.offset-md-3
    .text-center
      %h1 Edit Episode
    = render 'form'

app/views/episodes/index.html.haml
%h1.text-center Episodes
= render 'episode'

app/views/episodes/last.html.haml
.row
  .col-md-6.offset-md-3
    .text-center
      %h1 Last Episode
    = render 'episode_details'

app/views/episodes/new.html.haml
.row
  .col-md-6.offset-md-3
    .text-center
      %h1 New Episode
    = render 'form'

app/views/episodes/search.html.haml
%h2.text-center.mb-4="Search results for #{@query}"

- if @episodes.count == 0
  .alert.alert-info There were no results for your search
- else
  .row
    .col-12-md-4.offset-md-2
      .list-group
        = render @episodes

app/views/episodes/season.html.haml
%h1.text-center.mb-4 Season #{@number}
= render 'episode'

app/views/episodes/seasons.html.haml
.row.bottom-bar-container.pl-3
  .col-md-4.offset-md-4
    %h1.text-center.mb-4 Seasons
    %ul.list-group
      - @seasons.each_with_index do |season, n|
        %li{class: "list-group-item #{n % 2 == 0 ? 'list-group-item-success d-flex justify-content-between align-items-center' : 'list-group-item-warning d-flex justify-content-between align-items-center'}"}
          = link_to "Season #{season}", season_path(season)
          %span.badge.badge-pill.badge-dark="#{number_episodes(season)} episode"

app/views/episodes/show.html.haml
.row
  .col-md-6.offset-md-3
    .text-center
      %h1 Episode Show
    = render 'episode_details'

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-danger
  %button.navbar-toggler{type: "button", "data-toggle": "collapse", "data-target": "#navbarNav", "aria-controls": "navbarNav", "aria-expanded": "false", "aria-label": "Toggle navigation"}
    %span.navbar-toggler-icon

.navbar-nav
  - if user_signed_in?
    .dropdown
      %button#dropdownMenuButton.btn.btn-primary.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
        My account
      .dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
        = link_to "Profile", profile_path, class: "dropdown-item"
        = link_to "Sign out", sign_out_path, method: "delete", class: "dropdown-item"
    %ul.navbar-nav
      %li.navbar-item
      -# {class: active_class(root_path)}
      = link_to 'Home', root_path, class: "nav-link"
  - else
    = link_to 'Sign in', sign_in_path, class: 'nav-link'
- if current_user
  %nav.navbar.navbar-expand-lg.navbar-dark.bg-danger
    =link_to "My TV show", root_path, class: 'navbar-brand'
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li.nav-item.active
          = link_to "Seasons", seasons_path, class: 'nav-link'

        %li.nav-item
          = link_to "Episodes", episodes_path, class: 'nav-link'
        %li.nav-item
          = link_to "Last episode", last_episode_path, class: 'nav-link'
        = link_to " New Episode", new_episode_path, class: "btn btn-light"
      = form_tag search_path, class: "form-inline", method: "get" do
        = text_field_tag "query", @query, class:"form-control mr-sm-2", type:"search", placeholder:"Search episodes", "aria-label": "Search"
        = submit_tag "Search", class: "btn btn-light"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width", :name => "viewport"}/
    %title ViewsExercises
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = yield